### ISSUE TITLE
フラッピーバードを作る

### ISSUE THREAD

**Issue by ittokunvim** [ittokunvim/bevy-games#7]
フラッピーバードとは、画面のタップによって画面上を飛ぶ鳥の高さを調整し、土管の隙間をぶつけずに飛ばし続けるゲーム。

> https://ja.wikipedia.org/wiki/Flappy_Bird
> https://flappybird.io/

実装手順

- [x] プロジェクトの作成
- [x] プレイヤーのセットアップ
- [x] プレイヤーのジャンプ機能を実装
- [x] プレイヤーの重力処理を実装
- [x] 障害物のセットアップ
- [x] 障害物の移動処理を実装
- [x] 障害物が出現する処理を実装
- [x] 障害物が削除される処理を実装
- [x] 障害物の当たり判定を実装
- [x] スコアボードの実装
- [ ] READMEを編集

プレイヤーがジャンプしたら、ゲームを始めることにする。

プレイヤーが障害物に当たってしまったら、セットアップの画面に戻る。

BevyのTimerを使って、障害物の生成を行う。

スコアは、プレイヤーが障害物を超えたら+1、プレイヤーが障害物に当たったら-3とする。

**Comment by ittokun** [comment]
このゲームは横スクロールゲームだが、すでに完成されたマップがあるわけではなく、ランダムに生成された障害物をプログラム実行中に生成していくもの。イメージ的に言えば「チャリ走」みたいなもの。

もしかしたらプレイヤーの移動処理は必要ではなく、障害物に移動処理を実装したほうが良いのかもしれない。
